#cloud-config
coreos:
  update:
    reboot-strategy: etcd-lock
    group: alpha
  etcd2:
    discovery: ${ETCD_DISCOVERY_TOKEN}
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380
    heartbeat-interval: 500
    election-timeout: 5000
  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 50-cloud-init.conf
          content: |
            [Service]
            Restart=always
            RestartSec=5
            StartLimitInterval=0
