#cloud-config
coreos:
  update:
    reboot-strategy: etcd-lock
    group: alpha
  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 50-cloud-init.conf
          content: |
            [Service]
            Environment=ETCD_NAME=etcd${ETCD_INDEX}
            Environment=ETCD_INITIAL_CLUSTER_STATE=new
            Environment=ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
            Environment=ETCD_INITIAL_CLUSTER=${ETCD_ENDPOINTS}
            Environment=ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${ETCD_NETWORK_PREFIX}.${ETCD_INDEX}:2380
            Environment=ETCD_LISTEN_PEER_URLS=http://${ETCD_NETWORK_PREFIX}.${ETCD_INDEX}:2380
            Environment=ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            Environment=ETCD_ADVERTISE_CLIENT_URLS=http://${ETCD_NETWORK_PREFIX}.${ETCD_INDEX}:2379
            Environment=ETCD_HEARTBEAT_INTERVAL=500
            Environment=ETCD_ELECTION_TIMEOUT=5000
            Environment=ETCD_SNAPSHOT_COUNT=10000
            Environment=ETCD_MAX_SNAPSHOTS=5
            Environment=ETCD_MAX_WALS=5
            Environment=ETCD_DATA_DIR=/var/lib/etcd2-data
            Environment=ETCD_WAL_DIR=/var/lib/etcd2-wal
            Restart=always
            RestartSec=5
            StartLimitInterval=0
