#cloud-config
write_files:
  - path: /etc/flannel/options.env
    permissions: 0644
    owner: root:root
    content: |
      FLANNELD_IFACE=$private_ipv4
      FLANNELD_ETCD_ENDPOINTS=http://127.0.0.1:2379
coreos:
  update:
    reboot-strategy: best-effort
    group: alpha
  etcd2:
    discovery: ${ETCD_DISCOVERY_TOKEN}
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://$private_ipv4:2379,http://127.0.0.1:2379
    advertise-client-urls: http://$private_ipv4:2379
    heartbeat-interval: 500
    election-timeout: 5000
  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 50-cloud-init.conf
          content: |
            [Service]
            Restart=always
            RestartSec=5
            StartLimitInterval=0
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-cloud-init.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"${POD_NETWORK}","Backend":{"Type":"vxlan"}}'
            Restart=always
            RestartSec=5
            StartLimitInterval=0
    - name: docker.service
      command: start
      drop-ins:
        - name: 50-cloud-init.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
            [Service]
            Restart=always
            RestartSec=5
            StartLimitInterval=0
    - name: kubelet.service
      command: start
      content: |
        [Service]
        Environment=KUBELET_OPTS=
        ExecStart=/usr/bin/kubelet \
          --api-servers=http://127.0.0.1:8080 \
          --register-node=false \
          --allow-privileged=true \
          --config=/etc/kubernetes/manifests \
          --hostname-override=$private_ipv4 \
          --cluster-dns=${DNS_SERVICE_IP} \
          --cluster-domain=cluster.local \
          --cadvisor-port=0 \
          $KUBELET_OPTS
        Restart=always
        RestartSec=5
        StartLimitInterval=0
        [Install]
        WantedBy=multi-user.target
